version: "3.8"

services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-demo
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  backend:
    build:
      context: ./server
    image: server:1.0-sgu
    container_name: sgu-backend

    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-demo
      DB_USER: root
      DB_PASS: root

      SERVER_PORT: 8080
      SERVER_SSL_ENABLED: false

    ports:
      - "8081:8080" 
    networks:
      - sgu-net
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081       
        API_BASE: /api
        API_PROTOCOL: http
    image: client:1.0-sgu
    container_name: sgu-frontend

    ports:
      - "3001:80"
      - "3443:443"
    networks:
      - sgu-net
    depends_on:
      - backend
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    restart: unless-stopped

volumes:
  sgu-volume:
    external: false
  certbot-conf:
    external: true

networks:
  sgu-net:
    external: false